# question_data = [
# {"text": "A slug's blood is green.", "answer": "True"},
# {"text": "The loudest animal is the African Elephant.", "answer": "False"},
# {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
# {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
# {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
# {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
# {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
# {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
# {"text": "Google was originally called 'Backrub'.", "answer": "True"},
# {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
# {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
# {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

question_data = [

        {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In the survival horror game, Cry of Fear,; what was the name of Simon&#039;s"
                     " close friend potential love interest?",
         "correct_answer": "Sophie", "incorrect_answers": ["Olivia", "Jessica", "Alice"]},
        {"type": "multiple", "difficulty": "easy", "category": "Science &amp; Nature",
         "question": "What is the unit of electrical resistance?", "correct_answer": "Ohm",
         "incorrect_answers": ["Mho", "Tesla", "Joule"]},
        {"type": "boolean", "difficulty": "easy", "category": "Politics",
         "question": "The S in Harry S. Truman stands for &quot;Samuel&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Who created the &quot;Metal Gear&quot; Series?",
         "correct_answer": "Hideo Kojima",
         "incorrect_answers": ["Hiroshi Yamauchi", "Shigeru Miyamoto", "Gunpei Yokoi"]},
        {"type": "multiple", "difficulty": "easy",
         "category": "Entertainment: Cartoon &amp; Animations",
         "question": "What was the name of the sea witch in the 1989 Disney film &quot;The Little Mermaid&quot;?",
         "correct_answer": "Ursula",
         "incorrect_answers": ["Madam Mim", "Maleficent", "Lady Tremaine"]},
        {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Who is the founder of Team Fortress 2&#039;s fictional company &quot;Mann Co&quot;?",
         "correct_answer": "Zepheniah Mann",
         "incorrect_answers": ["Cave Johnson", "Wallace Breem", "Saxton Hale"]},
        {"type": "boolean", "difficulty": "easy", "category": "Geography",
         "question": "A group of islands is called an &#039;archipelago&#039;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
         "question": "Who was &quot;Kung Fu Fighting&quot; in 1974?",
         "correct_answer": "Carl Douglas",
         "incorrect_answers": ["The Bee Gees", "Heatwave", "Kool &amp; the Gang"]},
        {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
         "question": "Which of the following is not an Ivy League University?",
         "correct_answer": "Stanford",
         "incorrect_answers": ["University of Pennsylvania", "Harvard", "Princeton"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
         "question": "An average human can go two weeks without water.",
         "correct_answer": "False", "incorrect_answers": ["True"]}
]
